on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: zmkfirmware/zmk-build-arm:stable

    strategy:
      matrix:
        include:
          # - { board: hw75_keyboard@1.1, keymap: hw75_keyboard.keymap  }
          # - { board: hw75_keyboard@1.2, keymap: hw75_keyboard.keymap  }
          - { board: hw75_dynamic@A,    keymap: hw75_dynamic.keymap   }
          # - { board: hw75_dynamic@B,    keymap: hw75_dynamic.keymap   }

    steps:
      - name: Prepare variables
        run: |
          echo "zephyr_version=${ZEPHYR_VERSION}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build tools
        run: |
          apt-get update
          apt-get install -y python3-pip python3-venv python3-setuptools python3-wheel python3-full ninja-build protobuf-compiler
    
          # 创建虚拟环境并设置权限
          python3 -m venv /opt/venv
          chown -R $USER:$USER /opt/venv
          . /opt/venv/bin/activate
      
          # 在虚拟环境中安装依赖
          python3 -m pip install --upgrade pip
          python3 -m pip install fonttools
      
          # 安装 Node.js
          curl -fsSL https://deb.nodesource.com/setup_18.x | -E bash -
          apt-get install -y nodejs
      
          # 安装 lv_font_conv (使用--unsafe-perm避免权限问题)
          npm install -g lv_font_conv --unsafe-perm=true
      
          # 确保 pyftsubset 可用
          ln -sf /opt/venv/bin/pyftsubset /usr/local/bin/pyftsubset

      - name: Cache west modules
        uses: actions/cache@v3.0.11
        continue-on-error: true
        env:
          cache_name: cache-zephyr-${{ env.zephyr_version }}-modules
        with:
          path: |
            modules/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Prepare west
        run: |
          west init -l config
          west update
          west zephyr-export
          python3 -m venv .venv
          chmod +x .venv/bin/activate
          . .venv/bin/activate
          pip install  -r zephyr/scripts/requirements.txt
          git config --global --add safe.directory $PWD

      - name: West build
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config \
            -DKEYMAP_FILE=${GITHUB_WORKSPACE}/config/${{ matrix.keymap }}
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

      - name: Rename artifacts
        run: |
          mkdir build/artifacts
          if [ -f build/zephyr/zmk.uf2 ]; then
            cp build/zephyr/zmk.uf2 "build/artifacts/${{ matrix.board }}-zmk.uf2"
          fi
          if [ -f build/zephyr/zmk.hex ]; then
            cp build/zephyr/zmk.hex "build/artifacts/${{ matrix.board }}-zmk.hex"
          fi
          cp build/zephyr/zmk.bin "build/artifacts/${{ matrix.board }}-zmk.bin"

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/artifacts

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Prepare release notes
        id: release
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "RELEASE_BODY<<$EOF" >> $GITHUB_OUTPUT
          sed 's/{{TAG}}/${{ github.ref_name }}/g' .github/RELEASE_TEMPLATE.md >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Publish release
        uses: svenstaro/upload-release-action@v4
        with:
          file: firmware/*
          file_glob: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.release.outputs.RELEASE_BODY }}
          prerelease: true
